---

- name: restart sshd
  service: name=sshd state=restarted
  become: yes

- name: restart fail2ban
  service: name=fail2ban state=restarted
  become: yes

- name: restart iptables-persistent
  service: name=netfilter-persistent state=restarted
  become: yes

- name: restart mariadb
  service: name=mysql state=restarted
  become: yes

- name: restart nginx
  service: name=nginx state=restarted
  become: yes

- name: restart php-fpm
  service: name=php5-fpm state=restarted
  become: yes

- name: reload systemd
  command: systemctl daemon-reload
  become: yes

- name: restart varnish
  service: name="{{ item }}" state=restarted
  with_items: ['varnish', 'varnishlog', 'varnishncsa']
  become: yes
