---

debian_version: 'jessie'
timezone: 'America/New_York'

default_user: 'prikhi'
backup_directory: '/var/backups/wordpress'

ssh_port: '8282'
ssh_keys:
  - 'ecdsa-sha2-nistp521 AAAAE2VjZHNhLXNoYTItbmlzdHA1MjEAAAAIbmlzdHA1MjEAAACFBADPBNd6vqr8sjh5DZ6D7XVV/pWmaXpJzm/bgAPK9z/tHKaQXlG8nyuJdFinXZNBWEFGbjo9ZhmhIaehF6dW6aDm4gE4au8SUnJHFZdwmNgkmJjEBOPcRjbV15JWjU97w9WtjsPW43aDTpEiSFBH1FM2oLvuKO9ydTC20eEMnT94aj5Qdw== prikhi@Lucy'
sftp_keys:
  - 'ecdsa-sha2-nistp521 AAAAE2VjZHNhLXNoYTItbmlzdHA1MjEAAAAIbmlzdHA1MjEAAACFBADPBNd6vqr8sjh5DZ6D7XVV/pWmaXpJzm/bgAPK9z/tHKaQXlG8nyuJdFinXZNBWEFGbjo9ZhmhIaehF6dW6aDm4gE4au8SUnJHFZdwmNgkmJjEBOPcRjbV15JWjU97w9WtjsPW43aDTpEiSFBH1FM2oLvuKO9ydTC20eEMnT94aj5Qdw== prikhi@Lucy'
  - 'ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAvm7UjQ5VTZnwFME7TMRriyz+7Y5Vg87L4EsQdDHBY8WXhYpP6IwuGDcsdnqhLiD6h8sB6AX4T6c6xlIgjdLoYNnmqlH2lkurQjzA+0zS38SCz24fHfUL+D8y09wsQ1zJdxahrqIOoGY2G2Rsf3a+77L5E6gpaTepEifUow9UqQzyfO02aZQIND9MMQsRLSXm9jFwGaGaOCGdX0Dy/xRFIuKT8ULEEokcRNrXo7qVNJcOjEoWF9idHwJ/Ez2u7b0Q2oRoCJdMd01cvoWPupaaUih9TtchSJrANvGQe5rBX3uWIL1xiq7mSioAPJH/4/5lo0cL41fPJOTbRIm9HnMCiw== wvega@wvega.com'

fail2ban_whitelist:
  - '127.0.0.1/8'
  - '104.245.228.18'

website_hostname: "ic.org"
production_servername: "www"
staging_servername: "staging"

ssmtp_host: 'smtp.gmail.com'
ssmtp_port: 25
ssmtp_user: 'no-reply@{{ website_hostname }}'
ssmtp_use_tls: 'YES'
ssmtp_starttls: '{{ ssmtp_use_tls }}'
ssmtp_root_email: 'web.manager@{{ website_hostname }}'

nginx_http_port: 80
nginx_https_port: 443

adminer_subdomain: "adminer"
adminer_version: "4.2.4"
adminer_theme: "nette"
adminer_checksum: "sha256:bbe24e287f42cb3d1f272ebd890a8a4f81e4e675f88f726ae5f80347181e3fd6"
adminer_theme_checksum: "sha256:632965d2ca4440d73a27c47ac208da30e57ac018395411bcdd8528d108a56f2a"

mysql_key_buffer: "80M"
mysql_query_cache: "1000M"
mysql_innodb_buffer_pool_size: "1000M"
mysql_tmp_table_size: "256M"
mysql_max_heap_size: "256M"
mysql_table_open_cache: "800"

php_max_execution_time: 300
php_max_input_vars: 5000

php_max_children: 16
php_max_request_per_child: 1024
php_request_terminate_timeout: '300s'

php_apc:
  shm_segments: 1
  shm_size: 512M
  num_files_hint: 7000
  user_entries_hint: 4096
  ttl: 7200
  user_ttl: 7200
  gc_ttl: 3600
  stat: 1
  include_once_override: 0
  file_update_protection: 2
  max_file_size: 16M

varnish_port: 80
varnish_repo_version: '4.1'
varnish_file_limit: 131072
varnish_mem_limit: 82000
varnish_min_threads: 100
varnish_max_threads: 5000
varnish_thread_timeout: 120
varnish_storage_size: '1G'
varnish_storage_backend: 'malloc'
varnish_ttl: 120
varnish_connection_timeout: '600s'
varnish_max_connections: 800

wordpress_database_prefix: "3uOgy46w_"
