---

- name: Ensure the Basic Server Configuration is Correct
  include: setup.yml
  tags: setup

- name: Ensure the Default User is Properly Configured
  include: user.yml
  tags: user

- name: Ensure the Server is Properly Secured
  include: security.yml
  tags: security

- name: Ensure SSMTP is Correctly Configured
  include: ssmtp.yml
  tags: ssmtp, mail

- name: Ensure MySQL is Correctly Configured
  include: mysql.yml
  tags: mysql, web

- name: Ensure Nginx is Correctly Configured
  include: nginx.yml
  tags: nginx, web

- name: Ensure PHP-FPM is Correctly Configured
  include: php.yml
  tags: php, web

- name: Ensure Varnish is Correctly Configured
  include: varnish.yml
  tags: varnish, web

- name: Ensure the Wordpress Sites are Correctly Configured
  include: wordpress.yml
  tags: wordpress, web
