---

- name: Ensure the Basic Server Configuration is Correct
  include: setup.yml
  tags: setup

- name: Ensure the Default User is Properly Configured
  include: user.yml
  tags: user

- name: Ensure the Server is Properly Secured
  include: security.yml
  tags: security

- name: Ensure MySQL is Correctly Configured
  include: mysql.yml
  tags: mysql

- name: Ensure Nginx is Correctly Configured
  include: nginx.yml
  tags: nginx

- name: Ensure PHP-FPM is Correctly Configured
  include: php.yml
  tags: php

- name: Ensure Varnish is Correctly Configured
  include: varnish.yml
  tags: varnish
