---

- name: Ensure the Basic Server Configuration is Correct
  include: setup.yml
  tags: setup

- name: Ensure the Default User is Properly Configured
  include: user.yml
  tags: user

- name: Ensure the Server is Properly Secured
  include: security.yml
  tags: security

- name: Ensure MySQL is Correctly Configured
  include: mysql.yml
  tags: mysql
