---

- name: Ensure MariaDB and it's Supporting Modules are Installed
  apt: name="{{ item }}"
  with_items: ['mariadb-server', 'python-mysqldb']
  become: yes

- name: Ensure the MariaDB root User has a Password Set
  mysql_user: user=root password="{{ vaulted_mysql_root_password }}" host="localhost"
  ignore_errors: yes
  become: yes

- name: Ensure the MariaDB root User is Correctly Configured
  mysql_user: user=root password="{{ vaulted_mysql_root_password }}" host="{{ item }}"
              login_user=root login_password="{{ vaulted_mysql_root_password }}"
  with_items:
    - "::1"
    - "127.0.0.1"
    - "localhost"

- name: Ensure the Anonymous MariaDB Users are Removed
  mysql_user: user="" host="{{ item }}" state="absent"
              login_user=root login_password="{{ vaulted_mysql_root_password }}"
  with_items: ['{{ ansible_fqdn }}', 'localhost']

- name: Ensure Remote root Access for MariaDB is Disabled
  mysql_user: user="root" host="{{ ansible_fqdn }}" state=absent
              login_user=root login_password="{{ vaulted_mysql_root_password }}"

- name: Ensure the MariaDB test Database is Removed
  mysql_db: db=test state=absent
            login_user=root login_password="{{ vaulted_mysql_root_password }}"

- name: Ensure the production and staging MariaDB Databases Exist
  mysql_db: db="{{ item }}"
            login_user=root login_password="{{ vaulted_mysql_root_password }}"
  with_items: ['production', 'staging']

- name: Ensure the production and staging MariaDB Users are Correctly Configured
  mysql_user: user="{{ item.name }}" password="{{ item.pass }}"
              priv="{{ item.name }}.*:ALL" append_privs=yes host=localhost
              login_user=root login_password="{{ vaulted_mysql_root_password }}"
  with_items:
    - { name: "production",
        pass: "{{ vaulted_mysql_production_password }}" }
    - { name: "staging",
        pass: "{{ vaulted_mysql_staging_password }}" }

- name: Ensure MariaDB is Configured for Security
  ini_file: dest=/etc/mysql/my.cnf backup=yes section="mysqld"
            option="{{ item.option }}" value="{{ item.value }}"
  with_items:
    - { option: local-infile,
        value: 0 }
    - { option: bind-address,
        value: 127.0.0.1 }
  notify: restart mariadb
  become: yes

- name: Ensure MariaDB is Configured for Performance
  ini_file: dest=/etc/mysql/my.cnf backup=yes section="mysqld"
            option="{{ item.option }}" value="{{ item.value }}"
  with_items:
    - { option: key_buffer,
        value: "{{ mysql_key_buffer }}" }
    - { option: query_cache_limit,
        value: "{{ mysql_query_cache }}" }
    - { option: innodb_buffer_pool_size,
        value: "{{ mysql_innodb_buffer_pool_size }}" }
    - { option: tmp_table_size,
        value: "{{ mysql_tmp_table_size }}" }
    - { option: max_heap_table_size,
        value: "{{ mysql_max_heap_size }}" }
    - { option: table_open_cache,
        value: "{{ mysql_table_open_cache }}" }
  notify: restart mariadb
  become: yes
